# 389 Find the Difference
'''
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
'''
def findTheDifference(s, t):
    # use dict to store s
    # check if each character is in s
    # if it is not in the set, then it is the result
    from collections import defaultdict
    char_count_s = defaultdict(int)
    char_count_t = defaultdict(int)
    for char_s in s:
        char_count_s[char_s] += 1
    for char_t in t:
        if char_t not in char_count_s:
            return char_t
        char_count_t[char_t] += 1
    for key, value in char_count_t.items():
        if key in char_count_s and value > char_count_s[key]:
            return key

s = 'abcd'
t = 'abcde'
print(findTheDifference(s, t))